import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

export async function validateApiKey(apiKey: string): Promise<boolean> {
  if (!apiKey) return false;
  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`, {
      method: 'GET'
    });
    return response.ok;
  } catch (error) {
    console.error('API Key validation error:', error);
    throw error;
  }
}

interface CacheEntry {
  result: string;
  timestamp: number;
}

// Persistent disk cache setup
const cacheFilePath = path.join(os.homedir(), '.smartsweep_ai_cache.json');
let diskCache: Record<string, CacheEntry> = {};

function loadDiskCache(): void {
  try {
    if (fs.existsSync(cacheFilePath)) {
      const raw = fs.readFileSync(cacheFilePath, 'utf-8');
      diskCache = JSON.parse(raw) || {};
    }
  } catch {
    diskCache = {};
  }
}

function saveDiskCache(): void {
  try {
    fs.writeFileSync(cacheFilePath, JSON.stringify(diskCache, null, 2), 'utf-8');
  } catch (e) {
    console.warn('Failed to save AI disk cache', e);
  }
}

// Load cache on module initialization
loadDiskCache();

class SlidingWindowRateLimiter {
  private timestamps: number[] = [];
  private maxPerMinute: number = 5; // Cap at 5 requests / 60s (strictly 1 request per 12 seconds)

  async waitForSlot(): Promise<void> {
    while (true) {
      const now = Date.now();
      this.timestamps = this.timestamps.filter(ts => now - ts < 60000);

      if (this.timestamps.length < this.maxPerMinute) {
        this.timestamps.push(now);
        return;
      }

      const oldest = this.timestamps[0];
      const waitTimeMs = Math.max(500, 60000 - (now - oldest) + 500);
      await new Promise(resolve => setTimeout(resolve, waitTimeMs));
    }
  }
}

const rateLimiter = new SlidingWindowRateLimiter();
const CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hour persistent cache

async function callGeminiApi(apiKey: string, prompt: string, cacheKey?: string): Promise<string> {
  if (!apiKey) {
    throw new Error('API Key is required to get AI recommendations.');
  }

  if (cacheKey && diskCache[cacheKey]) {
    const cached = diskCache[cacheKey];
    if (Date.now() - cached.timestamp < CACHE_TTL_MS) {
      return cached.result;
    }
  }

  // List of models to try in order
  const models = ['gemini-2.5-flash', 'gemini-2.5-pro'];
  let lastErrorMsg = '';

  for (let attempt = 0; attempt < 2; attempt++) {
    // Wait for rate limit slot
    await rateLimiter.waitForSlot();

    const modelName = models[attempt % models.length];

    try {
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }]
        })
      });

      if (response.status === 429) {
        // Quota / Rate limit hit - sleep 8 seconds and retry automatically
        console.warn(`Gemini 429 Rate Limit (Attempt ${attempt + 1}/3). Retrying in 8s...`);
        await new Promise(res => setTimeout(res, 8000));
        continue;
      }

      if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        lastErrorMsg = err.error?.message || response.statusText || 'Failed to fetch AI response';
        if (response.status === 404 || lastErrorMsg.toLowerCase().includes('not found') || lastErrorMsg.toLowerCase().includes('quota') || lastErrorMsg.toLowerCase().includes('resource_exhausted')) {
          await new Promise(res => setTimeout(res, 2000));
          continue;
        }
        throw new Error(lastErrorMsg);
      }

      const data = await response.json();
      if (!data.candidates || data.candidates.length === 0) {
        throw new Error('No response generated by AI.');
      }

      const text = data.candidates[0].content.parts[0].text;
      if (cacheKey) {
        diskCache[cacheKey] = { result: text, timestamp: Date.now() };
        saveDiskCache();
      }
      return text;
    } catch (error: any) {
      console.error(`AI API Attempt ${attempt + 1} Error:`, error);
      lastErrorMsg = error.message;
      if (attempt < 2) {
        await new Promise(res => setTimeout(res, 4000));
      }
    }
  }

  if (lastErrorMsg.toLowerCase().includes('429') || lastErrorMsg.toLowerCase().includes('quota') || lastErrorMsg.toLowerCase().includes('resource_exhausted')) {
    throw new Error("⚠️ AI Rate Limit Reached: Your Gemini API key quota was reached. Please wait a minute or use a new key in Settings.");
  }

  throw new Error(lastErrorMsg || 'Failed to communicate with AI service.');
}

export function clearAiCache(): void {
  diskCache = {};
  saveDiskCache();
}

export async function generateCleanupAdvice(apiKey: string, scanSummary: any): Promise<string> {
  const prompt = `You are a helpful IT assistant. I have scanned my current system. Here is a summary of my storage:
${JSON.stringify(scanSummary, null, 2)}

Provide concise, plain-English advice on what I can safely delete. If top files are listed, specifically mention which of those exact files might be taking up the most space and whether they seem safe to remove (e.g. installers, temp files).`;

  const cacheKey = `${apiKey}_cleanup_${JSON.stringify(scanSummary)}`;
  return callGeminiApi(apiKey, prompt, cacheKey);
}

export async function explainPath(apiKey: string, targetPath: string): Promise<string> {
  const prompt = `You are a helpful IT assistant. A user is looking at this folder on their current system:
"${targetPath}"

Provide a concise, plain-English explanation (2-3 sentences) of what this folder typically contains, what application it belongs to (if known), and whether it is generally safe to delete its contents to free up space. Format your response in markdown.`;

  const cacheKey = `${apiKey}_explain_${targetPath}`;
  return callGeminiApi(apiKey, prompt, cacheKey);
}

export async function analyzeStartup(apiKey: string, items: any[]): Promise<string> {
  const prompt = `You are a helpful IT assistant. Here is a list of my system startup items:
${JSON.stringify(items, null, 2)}

Provide a concise, plain-English recommendation on which items I should safely disable to improve my boot times.`;

  const cacheKey = `${apiKey}_startup_${JSON.stringify(items.map(i => ({ name: i.name, enabled: i.enabled })))}`;
  return callGeminiApi(apiKey, prompt, cacheKey);
}
