export async function validateApiKey(apiKey: string): Promise<boolean> {
  if (!apiKey) return false;
  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`, {
      method: 'GET'
    });
    return response.ok;
  } catch (error) {
    console.error('API Key validation error:', error);
    throw error;
  }
}

interface CacheEntry {
  result: string;
  timestamp: number;
}

const aiCache = new Map<string, CacheEntry>();
const CACHE_TTL_MS = 5 * 60 * 1000; // 5 minute in-memory cache to conserve API quota

async function callGeminiApi(apiKey: string, prompt: string, cacheKey?: string): Promise<string> {
  if (!apiKey) {
    throw new Error('API Key is required to get AI recommendations.');
  }

  if (cacheKey) {
    const cached = aiCache.get(cacheKey);
    if (cached && (Date.now() - cached.timestamp < CACHE_TTL_MS)) {
      return cached.result;
    }
  }

  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }]
        }]
      })
    });

    if (!response.ok) {
      const err = await response.json().catch(() => ({}));
      const rawMsg = err.error?.message || response.statusText || 'Failed to fetch AI response';
      
      if (response.status === 429 || rawMsg.toLowerCase().includes('quota') || rawMsg.toLowerCase().includes('resource_exhausted')) {
        throw new Error("⚠️ AI Rate Limit Reached: You've exceeded your Gemini API request quota (20 requests/min). Please wait a minute before requesting advice again.");
      }
      throw new Error(rawMsg);
    }

    const data = await response.json();
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No response generated by AI.');
    }

    const text = data.candidates[0].content.parts[0].text;
    if (cacheKey) {
      aiCache.set(cacheKey, { result: text, timestamp: Date.now() });
    }
    return text;
  } catch (error: any) {
    console.error('AI API Error:', error);
    throw error;
  }
}

export function clearAiCache(): void {
  aiCache.clear();
}

export async function generateCleanupAdvice(apiKey: string, scanSummary: any): Promise<string> {
  const prompt = `You are a helpful IT assistant. I have scanned my current system. Here is a summary of my storage:
${JSON.stringify(scanSummary, null, 2)}

Provide concise, plain-English advice on what I can safely delete. If top files are listed, specifically mention which of those exact files might be taking up the most space and whether they seem safe to remove (e.g. installers, temp files).`;

  const cacheKey = `${apiKey}_cleanup_${JSON.stringify(scanSummary)}`;
  return callGeminiApi(apiKey, prompt, cacheKey);
}

export async function explainPath(apiKey: string, targetPath: string): Promise<string> {
  const prompt = `You are a helpful IT assistant. A user is looking at this folder on their current system:
"${targetPath}"

Provide a concise, plain-English explanation (2-3 sentences) of what this folder typically contains, what application it belongs to (if known), and whether it is generally safe to delete its contents to free up space. Format your response in markdown.`;

  const cacheKey = `${apiKey}_explain_${targetPath}`;
  return callGeminiApi(apiKey, prompt, cacheKey);
}

export async function analyzeStartup(apiKey: string, items: any[]): Promise<string> {
  const prompt = `You are a helpful IT assistant. Here is a list of my system startup items:
${JSON.stringify(items, null, 2)}

Provide a concise, plain-English recommendation on which items I should safely disable to improve my boot times.`;

  const cacheKey = `${apiKey}_startup_${JSON.stringify(items.map(i => ({ name: i.name, enabled: i.enabled })))}`;
  return callGeminiApi(apiKey, prompt, cacheKey);
}
