export async function validateApiKey(apiKey) {
    if (!apiKey)
        return false;
    try {
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`, {
            method: 'GET'
        });
        return response.ok;
    }
    catch (error) {
        console.error('API Key validation error:', error);
        throw error;
    }
}
export async function generateCleanupAdvice(apiKey, scanSummary) {
    if (!apiKey) {
        throw new Error('API Key is required to get AI recommendations.');
    }
    try {
        const prompt = `You are a helpful IT assistant. I have scanned my Windows system. Here is a summary of my storage:
${JSON.stringify(scanSummary, null, 2)}

Provide concise, plain-English advice on what I can safely delete. If top files are listed, specifically mention which of those exact files might be taking up the most space and whether they seem safe to remove (e.g. installers, temp files).`;
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                contents: [{
                        parts: [{ text: prompt }]
                    }]
            })
        });
        if (!response.ok) {
            const err = await response.json();
            throw new Error(err.error?.message || 'Failed to fetch AI recommendation');
        }
        const data = await response.json();
        if (!data.candidates || data.candidates.length === 0) {
            throw new Error('No response generated by AI.');
        }
        return data.candidates[0].content.parts[0].text;
    }
    catch (error) {
        console.error('AI API Error:', error);
        throw error;
    }
}
export async function explainPath(apiKey, targetPath) {
    if (!apiKey) {
        throw new Error('API Key is required to get AI recommendations.');
    }
    try {
        const prompt = `You are a helpful IT assistant. A user is looking at this folder on their Windows PC:
"${targetPath}"

Provide a concise, plain-English explanation (2-3 sentences) of what this folder typically contains, what application it belongs to (if known), and whether it is generally safe to delete its contents to free up space. Format your response in markdown.`;
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                contents: [{
                        parts: [{ text: prompt }]
                    }]
            })
        });
        if (!response.ok) {
            const err = await response.json();
            throw new Error(err.error?.message || 'Failed to fetch AI explanation');
        }
        const data = await response.json();
        if (!data.candidates || data.candidates.length === 0) {
            throw new Error('No response generated by AI.');
        }
        return data.candidates[0].content.parts[0].text;
    }
    catch (error) {
        console.error('AI API Error:', error);
        throw error;
    }
}
export async function analyzeStartup(apiKey, items) {
    if (!apiKey) {
        throw new Error('API Key is required to get AI recommendations.');
    }
    try {
        const prompt = `You are a helpful IT assistant. Here is a list of my Windows startup items:
${JSON.stringify(items, null, 2)}

Provide a concise, plain-English recommendation on which items I should safely disable to improve my boot times.`;
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                contents: [{
                        parts: [{ text: prompt }]
                    }]
            })
        });
        if (!response.ok) {
            const err = await response.json();
            throw new Error(err.error?.message || 'Failed to fetch AI recommendation');
        }
        const data = await response.json();
        if (!data.candidates || data.candidates.length === 0) {
            throw new Error('No response generated by AI.');
        }
        return data.candidates[0].content.parts[0].text;
    }
    catch (error) {
        console.error('AI API Error:', error);
        throw error;
    }
}
